---
  - name: Chatbot Master Playbook
    gather_facts: no

    hosts: "all"

  - name: Importing chatbotCreateFilesystem
    import_playbook: chatbotCreateFilesystem.yml hosts2manage="{{ h2m | default("managedhosts") }}"

  - name: Importing chatbotInstallPythonDependencies
    import_playbook: chatbotInstallPythonDependencies.yml hosts2manage="{{ h2m | default("managedhosts") }}"
    when:
      - hostvars[inventory_hostname]['proceedWithInstallation']

  - name: Importing chatbotInstallSoftware
    import_playbook: chatbotInstallSoftware.yml hosts2manage="{{ h2m | default("managedhosts") }}"
    when:
      - hostvars[inventory_hostname]['proceedWithInstallation']

  - name: Importing chatbotStartServices
    import_playbook: chatbotStartServices.yml hosts2manage="{{ h2m | default("managedhosts") }}"
    when:
      - hostvars[inventory_hostname]['proceedWithInstallation']



### Reversing the playbook's changes
### systemctl stop ansibleChatbot && systemctl disable ansibleChatbot && systemctl stop ansibleChatbotWebInterface && systemctl disable ansibleChatbotWebInterface
### rm -rf /etc/systemd/system/ansibleChatbot.service && rm -rf /etc/systemd/system/ansibleChatbotWebInterface.service && rm -rf /home/chatbot/* && firewall-cmd --permanent --remove-port=8080/tcp && firewall-cmd --permanent --remove-port=9095/tcp
### /usr/bin/yes | pip3 uninstall nltk tflearn numpy tensorflow flask && yum remove python36 -y && yum remove git -y && yum remove nmap-ncat  -y
### umount /home/chatbot && rm -rf /home/chatbot && lvremove /dev/chatbotVG/data && vgremove chatbotVG && pvremove /dev/sdb /dev/sdc
